### ISSUE TITLE
Record Video playing in background

### ISSUE THREAD

**Issue by nedimf** [bgayman/FlipBook#1]
Hi, amazing library. Really good job!
I had success using it to record animation of the view. Now I want to see how to record video from AVPlayerLayer in background.

What do you recommend I can use? 
I saw there is something called ```shouldUseReplayKit``` is that what I need?

**Comment by nedimf** [comment]
Just a update on this, I decided to write my own Video rendering for this use case.

**Comment by namdhis** [comment]
> Just a update on this, I decided to write my own Video rendering for this use case.

Hi @nedimf . Could you share us the way you record video from AVPlayerLayer please. Thank you!
